VLO/Models/Turnos.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VLO.Models
{
    public class Turnos
    {
        [Key]
        public int IdTurno { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(3, ErrorMessage = "No puede ingresar menos de 3 caracteres")]
        [MaxLength(25, ErrorMessage = "No puede ingresar más de 25 caracteres")]
        [Display(Name = "Turno")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Display(Name = "Hora de inicio")]
        [DataType(DataType.Time)]
        public string HoraInicial { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [Display(Name = "Hora de finalización")]
        [DataType(DataType.Time)]
        public string HoraFinal { get; set; }


        //Relaciones 
        public virtual List<AsignacionTurno> AsignacionTurno { get; set; }
    }
}

VLO/Controllers/TurnosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VLO.Models;

namespace VLO.Controllers
{
    public class TurnosController : Controller
    {
        private Context db = new Context();

        // GET: Turnos
        public ActionResult Index()
        {
            return View(db.Turnos.ToList());
        }

        // GET: Turnos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turnos turnos = db.Turnos.Find(id);
            if (turnos == null)
            {
                return HttpNotFound();
            }
            return View(turnos);
        }

        // GET: Turnos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Turnos/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTurno,Nombre,HoraInicial,HoraFinal")] Turnos turnos)
        {
            if (ModelState.IsValid)
            {
                db.Turnos.Add(turnos);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(turnos);
        }

        // GET: Turnos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turnos turnos = db.Turnos.Find(id);
            if (turnos == null)
            {
                return HttpNotFound();
            }
            return View(turnos);
        }

        // POST: Turnos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTurno,Nombre,HoraInicial,HoraFinal")] Turnos turnos)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turnos).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(turnos);
        }

        // GET: Turnos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Turnos turnos = db.Turnos.Find(id);
            if (turnos == null)
            {
                return HttpNotFound();
            }
            return View(turnos);
        }

        // POST: Turnos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Turnos turnos = db.Turnos.Find(id);
            db.Turnos.Remove(turnos);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VLO/Views/Turnos/Create.cshtml
@model VLO.Models.Turnos

@{
    ViewBag.Title = "Agregar";
}

<h2>Nuevo Turno</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraInicial, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HoraFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraFinal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-info" /> |
                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
}

VLO/Views/Turnos/Delete.cshtml
@model VLO.Models.Turnos

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminando Turnos...</h2>

<h3>¿Estas seguro que quieres eliminarlo?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraInicial)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraInicial)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HoraFinal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HoraFinal)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

    <div class="form-actions col-md-8">
        <input type="submit" value="Eliminar" class="btn btn-danger" /> |
        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
    </div>
    }
</div>

VLO/Views/Turnos/Edit.cshtml
@model VLO.Models.Turnos

@{
    ViewBag.Title = "Editar";
}

<h2>Modificar Turno</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.IdTurno)

    <div class="col-md-8">
        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="col-md-8">
        <div class="form-group">
            @Html.LabelFor(model => model.HoraInicial, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraInicial, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraInicial, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            @Html.LabelFor(model => model.HoraFinal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HoraFinal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HoraFinal, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
    <div class="col-md-8">
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-info" />
                @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-default" })
            </div>
        </div>
    </div>
</div>
    }

VLO/Views/Turnos/Index.cshtml
@model IEnumerable<VLO.Models.Turnos>

@{
    ViewBag.Title = "Agregar";
}

<h2>Turnos</h2>

<p>
    <a href="@Url.Action("Create","Turnos")" class="btn btn-success"> <i class="glyphicon glyphicon-plus"></i> Nuevo</a>
</p>
<div class="row col-md-12 table-responsive" style="margin-top:10px">
    <table class="table table-bordered" style="background-color:#FFF">
        <tr style="background-color:#E6E6E6">
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraInicial)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HoraFinal)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraInicial)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.HoraFinal)
                </td>
                <td>
                    @Html.ActionLink(" ", "Edit", new { id = item.IdTurno }, new { @class = "btn btn-warning glyphicon glyphicon-refresh" }) | 
                    @Html.ActionLink(" ", "Delete", new { id = item.IdTurno }, new { @class = "btn btn-danger glyphicon glyphicon-trash" })
                </td>
            </tr>
        }

    </table>
</div>