VLO/Models/Menu.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VLO.Models
{
    public class Menu
    {
        [Key]
        public int IdMenu{ get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(3, ErrorMessage = "No puede ingresar menos de 3 caracteres")]
        [MaxLength(75, ErrorMessage = "No puede ingresar más de 75 caracteres")]
        [Display(Name = "Nombre Menú ")]
        public string Nombre { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [DataType(DataType.Currency)]
        [Display(Name = "Precio ")]
        public double Precio { get; set; }

        [Required(ErrorMessage = "Este campo es requerido")]
        [MinLength(3, ErrorMessage = "No puede ingresar menos de 3 caracteres")]
        [MaxLength(500, ErrorMessage = "No puede ingresar más de 500 caracteres")]
        [DataType(DataType.Text)]
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        

        //Relación con Tipo de Menu
        public int IdTipoMenu { get; set; }
        public virtual TipoMenu TipoMenu { get; set; }

        //Listar tabla en DetallePedido
        public virtual List<DetallePedido> DetallePedido { get; set; }

    }
}

VLO/Models/OrdenesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace VLO.Models
{
    public class OrdenesViewModel
    {
        public List<Menu> Menus { get; set; }
        public List<TipoMenu> TiposMenu { get; set; }
        public List<Productos> Productos { get; set; }
        public List<Pedido> Pedido { get; set; }
        public List<DetallePedido> DetallePedido { get; set; }
        public List<Mesa> Mesa { get; set; }
    }
}

VLO/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VLO.Models;

namespace VLO.Controllers
{
    public class MenusController : Controller
    {
        private Context db = new Context();

        // GET: Menus
        public ActionResult Index()
        {
            var menus = db.Menus.Include(m => m.TipoMenu);
            return View(menus.ToList());
        }
        [HttpPost]
        public ActionResult Index(string txtbuscar)
        {
            var listar = db.Menus;
            var query = (from p in listar where p.Nombre.Contains(txtbuscar) select p);
            return View(query.ToList());
        }


        // GET: Menus/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // GET: Menus/Create
        public ActionResult Create()
        {
            ViewBag.IdTipoMenu = new SelectList(db.TipoMenus, "IdTipoMenu", "Nombre");
            return View();
        }

        // POST: Menus/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdMenu,Nombre,Precio,Descripcion,IdTipoMenu")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Menus.Add(menu);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.IdTipoMenu = new SelectList(db.TipoMenus, "IdTipoMenu", "Nombre", menu.IdTipoMenu);
            return View(menu);
        }

        // GET: Menus/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdTipoMenu = new SelectList(db.TipoMenus, "IdTipoMenu", "Nombre", menu.IdTipoMenu);
            return View(menu);
        }

        // POST: Menus/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdMenu,Nombre,Precio,Descripcion,IdTipoMenu")] Menu menu)
        {
            if (ModelState.IsValid)
            {
                db.Entry(menu).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdTipoMenu = new SelectList(db.TipoMenus, "IdTipoMenu", "Nombre", menu.IdTipoMenu);
            return View(menu);
        }

        // GET: Menus/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Menu menu = db.Menus.Find(id);
            if (menu == null)
            {
                return HttpNotFound();
            }
            return View(menu);
        }

        // POST: Menus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Menu menu = db.Menus.Find(id);
            db.Menus.Remove(menu);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VLO/Controllers/OrdenesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using VLO.Models;

namespace VLO.Controllers
{
    public class OrdenesController : Controller
    {
        private Context db = new Context();

        // GET: Ordenes
        public ActionResult Index()
        {
            OrdenesViewModel All = new OrdenesViewModel();
            All.DetallePedido = db.DetallePedido.ToList();
            All.Pedido = db.Pedido.ToList();
            All.Mesa = db.Mesa.ToList();
            return View(All);
        }

        public ActionResult Ordenes()
        {
            var orden = db.Pedido./*Where(x => x.Estado == 1).*/ToList();
            var detalle = db.DetallePedido.Where(x => x.Estado == 1).ToList();
            CocinaViewModel cvm = new CocinaViewModel();
            cvm.pedidos = orden;
            cvm.detalle = detalle;
            cvm.menus = db.Menus.ToList();
            

            
            return View(cvm);
        }

        


        [HttpGet]
        public ActionResult TerminarOrdenCocina(int iddetalle)
        {
            
            DetallePedido dp = db.DetallePedido.Find(iddetalle);
            dp.Estado = 2;
            db.Entry(dp).State = EntityState.Modified;
            db.SaveChanges();

            var pe = db.Pedido.Find(dp.IdPedido);
            var detped = (from u in db.DetallePedido where u.IdPedido == pe.IdPedido select u).ToList();
            //Recorrer
            foreach (var io in detped)
            {
                
               
                Pedido de = db.Pedido.Find(io.IdPedido);
                de.Estado = 2;
                db.Entry(de).State = EntityState.Modified;
                db.SaveChanges();

            }


           

            return Redirect("/Ordenes/Ordenes");
        }

        public ActionResult OrdenesTerminadas()
        {
            var orden = db.Pedido/*.Where(x => x.Estado == 2)*/.ToList();
            var detalle = db.DetallePedido.Where(x => x.Estado == 2).ToList();
            CocinaViewModel cvm = new CocinaViewModel();
            cvm.pedidos = orden;
            cvm.detalle = detalle;
            cvm.menus = db.Menus.ToList();
            return View(cvm);
        }

        public ActionResult OrdenesMeseros(int idpedido)
        {
            Session["pedidoid"] = idpedido;
            //Pedido p = db.Pedido.Find(idpedido);
            //p.Estado = 3;
            //db.Entry(p).State = EntityState.Modified;
            //db.SaveChanges();

            return Redirect("/Ordenes/Pagos");
        }

        



        //VistaMenu
        public ActionResult Menu(int? id, int? idPedido)
        {
            Session["pedido"] = idPedido;
            Session["mesa"] = id;

            ViewBag.mesa = id;
           
                
                var pedido = Convert.ToInt32(Session["pedido"]);
            var mesa= Convert.ToInt32(Session["mesa"]);
            if (pedido>0)
                {
                    var cli = (from p in db.Pedido where p.IdPedido == pedido && p.IdMesa==mesa select p).FirstOrDefault();
                    ViewBag.cliente = cli.Cliente;
                    ViewBag.cantidad = cli.Cantidad;
                }
            
            
            var queryOrd = db.DetallePedido.Where(d => d.IdPedido == idPedido).ToList();
            OrdenesViewModel ovm = new OrdenesViewModel();
            ovm.DetallePedido = queryOrd;
            ovm.Menus = db.Menus.ToList();
            ovm.TiposMenu = db.TipoMenus.ToList();
            return View(ovm);
        }


        //Agregar orden y guardar datos en las diferentes tablas
        [HttpPost]
        public async Task<ActionResult> AddOrden(AddOrdenViewModel aovm)
        {
            //Usuarios e = db.Usuarios.Where(x => x.IdUser == 1).FirstOrDefault();
            int user = Convert.ToInt32(Session["Id"]);

            var ps = Convert.ToInt32(Session["pedido"]);
            if ( ps== 0)
            {
                Pedido p = new Pedido();
                p.Cantidad = aovm.numpersonas;
                p.Cliente = aovm.cliente;
                p.IdUser = user;
                p.Estado = 1;
                p.IdMesa = aovm.mesa;
            db.Pedido.Add(p);
            await db.SaveChangesAsync();
                Session["pedido"] = p.IdPedido;
                Session["mesa"] = p.Mesa;
            }
            

            var lastPedido = db.Pedido.OrderByDescending(x=>x.IdPedido).First();
            for(var i= 0;i < aovm.id.Count;i++)
            {
                DetallePedido dp = new DetallePedido();
                dp.IdMenu = aovm.id[i];
                dp.cantidad = aovm.cantidad[i];
                dp.IdPedido = Convert.ToInt32(Session["pedido"]);
                dp.sesion = Convert.ToInt32(Session["session"]);
                dp.Estado = 1;
                dp.Termino = aovm.termino;
                db.DetallePedido.Add(dp);
                await db.SaveChangesAsync();

                //Encontrar el menu
                var menu = db.Menus.Find(dp.IdMenu);
                //Buscar los menus en la receta
                var recmenu = (from u in db.Receta where u.IdMenu == menu.IdMenu select u).ToList();
                //Recorrer
                foreach (var io in recmenu)
                {
                    //Encontrar los productos que se utilizan
                    Productos de = db.Productos.Find(io.IdProducto);
                    
                    //Resta de la cantidad que se pide menos la cantidad utilizada

                    var Descuento = io.CantidadUtilizada * dp.cantidad;
                    de.Cantidad =de.Cantidad - Descuento;
                    db.Entry(de).State = EntityState.Modified;
                    db.SaveChanges();
                }
            }

            //Encontrar las mesas
            Mesa d = db.Mesa.Find(aovm.mesa);
            //Cambia el estado de la mesa
            d.Estado = false;
            db.Entry(d).State = EntityState.Modified;
            db.SaveChanges();

            return Redirect("Index");
        }

        //public async Task<ActionResult> DeleteDetalle(string key, string key2)
        //{
        //    try
        //    {
        //        var header = new Dictionary<string, string>()
        //        {
        //            {"IdDetalle",key }
        //        };
        //        DetallePedido dp = db.DetallePedido.Find(key);
        //        db.DetallePedido.Remove(dp);
        //        await db.SaveChangesAsync();
        //    }
        //    catch { }
        //    return RedirectToAction("Menu", new { IdMesa = key2 });
        //}

        [HttpGet]
        public ActionResult Pagos()
        {
            var idpedido = Convert.ToInt32(Session["pedidoid"]);
            var orden = db.Pedido.Where(x => x.Estado == 2).ToList();
            var queryOrd = db.DetallePedido.Where(d => d.IdPedido == idpedido).ToList();
            CocinaViewModel cvm = new CocinaViewModel();
            cvm.pedidos = orden;
            cvm.detalle = queryOrd;
            cvm.menus = db.Menus.ToList();
            return View(cvm);
        }

        [HttpPost]
        public ActionResult RealizarPago(double txttotal,int idPedido, int idDetalle, double Descuento, string Descripcion, double propina, AddOrdenViewModel cvm)
        {
            
            //Session["pedido"] = 0;
            //Session["mesa"] = 0;
            //Session["pedidoid"]= 0;
            Session.Remove("pedidoid");
            Session.Clear();
            Session["pedidoid"]=0;
            Session.Remove("pedido");
            Session.Clear();
            Session["pedido"] = 0;
            Session.Remove("mesa");
            Session.Clear();
            Session["mesa"] = 0;
            Factura p = new Factura();
            //p.NumFactura =1;
            p.IdDetalle = idDetalle;
            p.Precio = txttotal;
            p.Descuento = Descuento;
            p.Descripcion = Descripcion;
            p.Propina = propina;
            p.FechaFactura = Convert.ToString(DateTime.Now.Date);
            db.Factura.Add(p);
            db.SaveChanges();


            //var detalle = db.DetallePedido.Find(p.IdDetalle);
            //var det = (from x in db.DetallePedido where x.IdDetalle == detalle.IdDetalle select x).ToList();
            var det = (from x in db.DetallePedido where x.IdPedido == idPedido select x).ToList();
            foreach (var i in det)
            {
                DetallePedido de = db.DetallePedido.Find(i.IdDetalle);
                de.Estado = 3;
                db.Entry(de).State = EntityState.Modified;
                db.SaveChanges();


            }

            //Buscar cada Pedido
            var pedido = (from u in db.Pedido where u.IdPedido == idPedido select u).ToList();
            //Recorrer
            foreach (var io in pedido)
            {
                Pedido pe = db.Pedido.Find(io.IdPedido);
                pe.Estado = 3;
                db.Entry(pe).State = EntityState.Modified;
                db.SaveChanges();
            }


            //var dm = db.Mesa.Find(idDetalle);
            //var mesa = (from x in db.Mesa where x.IdMesa == dm.IdMesa select x);

            //foreach (var i in mesa)
            //{
            //    Mesa d = db.Mesa.Find(i.IdMesa);
            //    d.Estado = true;
            //    db.Entry(d).State = EntityState.Modified;
            //    db.SaveChanges();
            //    return Redirect("Index");


            //}
            return Redirect("Index");
        }
        

    }
}

VLO/Views/Ordenes/Index.cshtml
@model VLO.Models.OrdenesViewModel
@{
    ViewBag.Title = "Index";
}
<h2>Mesas</h2>

<br />
<br />
<br />
@{

    <div class="row col-md-12">
        @foreach (var item in Model.Pedido)
        {
            var classfilter = "Disponible";
            if (item.Mesa.Estado == false)
            {
                classfilter = "Ocupada";
            }
            <a class="all @classfilter" href="/Ordenes/Menu/@item.IdMesa">
                <div class="col-md-4">
                    <div class="thumbnail">
                        <div class="caption">
                            <h3>Mesa @item.Mesa.NumMesa</h3>
                        </div>
                        <div>
                            @if (item.Mesa.Estado == true)
                            {
                                <a href="/Ordenes/Menu/@item.IdMesa?idPedido = @item.IdPedido" class='@(item.Mesa.Estado==true?"btn btn-success":"btn btn-danger") m-l-10 m-b-10'>@(item.Mesa.Estado == true ? "Disponible" : "Ocupada")</a>
                            }
                            else if (item.Mesa.Estado == false)
                            {
                                <a href="/Ordenes/Menu/@item.IdMesa?idPedido=@item.IdPedido" class='@(item.Mesa.Estado==true?"btn btn-success":"btn btn-danger") m-l-10 m-b-10'>@(item.Mesa.Estado == true ? "Disponible" : "Ocupada")</a>

                            }
                        </div>
                    </div>
                </div>
            </a>
        }
    </div>
    <div class="row col-md-12">
        @foreach (var item in Model.Mesa)
        {
            var classfilter = "Disponible";
            if (item.Estado == false)
            {
                classfilter = "Ocupada";
            }
            if (item.Estado == true)
            {
                <a class="all @classfilter" href="/Ordenes/Menu/@item.IdMesa">
                    <div class="col-md-4">
                        <div class="thumbnail">
                            <div class="caption">
                                <h3>Mesa @item.NumMesa</h3>
                            </div>
                            <div>

                                <a href="/Ordenes/Menu/@item.IdMesa" class='@(item.Estado==true?"btn btn-success":"btn btn-danger") m-l-10 m-b-10'>@(item.Estado == true ? "Disponible" : "Ocupada")</a>

                            </div>
                        </div>
                    </div>
                </a>
            }
        }
    </div>
}

<script>
    function Filter(text) {
        if (text == ".all") {
            $(".all").show()
            return;
        }
        $(".all").hide()
        $(text).show();
    }
</script>

VLO/Views/Ordenes/Menu.cshtml
@model VLO.Models.OrdenesViewModel
@{
    ViewBag.Title = "Menu";
    int Item = 1;
    var IdOrden = "0";
    try
    {
        IdOrden = Convert.ToString(Model.DetallePedido.FirstOrDefault().IdDetalle);
    }
    catch
    {
        IdOrden = "0";
    }
}

<h2>Orden Mesa @ViewBag.mesa</h2>

<div class="col-md-12">
    <div class="col-md-6">
        <form action="/Ordenes/AddOrden" method="post">
            <div class="form-group">
                <label>Cliente</label>
                <input type="text" name="cliente" value="@ViewBag.cliente" class="form-control" required />
            </div>
            <div class="form-group">
                <label>Cantidad de Personas</label>
                <input type="number" class="form-control" min="1" max="10" name="numpersonas" value="@ViewBag.cantidad" required />
            </div>
            <input type="hidden" name="mesa" value="@ViewBag.mesa" />

            <table class="table table-bordered table-responsive" style="background-color:#FFF">
                <thead>
                    <tr>
                        <td>N°</td>
                        <td>Producto</td>
                        @*<td>Término</td>*@
                        <td>Estado</td>
                        <td>Cantidad</td>
                        <td>Precio</td>
                        <td>Total</td>
                        <td></td>
                    </tr>
                </thead>
                <tbody id="detalle">
                    @foreach (var item in Model.DetallePedido)
                    {
                        double total = item.cantidad * item.Menu.Precio;
                        <tr>
                            <td scope="row">@Item</td>
                            <td>@item.Menu.Nombre</td>
                            @*<td>@item.Termino</td>*@
                            <td>
                                @if (item.Estado == 1)
                                {
                                    <span class="badge badge-danger">
                                        En Cocina
                                    </span>
                                }
                                else if (item.Estado == 2)
                                {
                                    <span class="badge badge-success">
                                        Terminado
                                    </span>
                                }
                                else if (item.Estado == 3)
                                {
                                    <span class="badge badge-dark">
                                        Pagado
                                    </span>
                                }
                                
                                </td>

                                <td>@item.cantidad</td>
                            <td class="color-primary">$ @item.Menu.Precio</td>
                            <td class="color-primary">$ @total</td>
                            <td>
                                @using (Html.BeginForm())
                                {
                                    @Html.AntiForgeryToken()

                                <a href="@Url.Action("DeleteDetalle","Ordenes")" class="btn"><i class="ti ti-close"></i></a>
                                }
                            </td>
                        </tr>
                        Item = Item + 1;
                    }
                </tbody>
            </table>
            <a href="@Url.Action("Index","Ordenes")" class="btn btn-danger btn-rounded">Cancelar</a>
            <button type="submit" class="btn btn-green btn-rounded">Enviar a cocina</button>

        </form>
    </div>
    <div class="col-md-6">
        <h3 style="font-weight:bold">Menus</h3>
        <label class="btn btn-default" onclick="Filter('.all')">
            <input type="radio" name="options" id="option1" autocomplete="off" checked=""> All
        </label>
        @foreach (var item in Model.TiposMenu)
        {
            <label class="btn btn-default" onclick="Filter('.tipo_@item.IdTipoMenu')">
                <input type="radio" name="options" id="option1" autocomplete="off" checked=""> @item.Nombre
            </label>
        }
            <div class="col-md-12" style="margin-top:10px;height:450px; overflow:auto">
        @foreach (var item in Model.Menus)
        {
            <div class="col-md-6 all tipo_@item.IdTipoMenu">
                <div class="thumbnail">
                    <div class="caption">
                        <h3>@item.Nombre</h3>
                        <h4>@item.Precio.ToString("C")</h4>
                        <p>
                            <a data-toggle="modal" data-target="#modal_@item.IdMenu" class="btn btn-green">Ordenar</a>
                        </p>
                    </div>
                </div>
            </div>

            <!-- Modal -->
            <div class="modal fade" id="modal_@item.IdMenu" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="myModalLabel">Descripcion del Menu</h4>
                        </div>
                        <div class="modal-body">
                            <h1>@item.Nombre</h1>
                            <h2>@item.Precio.ToString("C")</h2>
                            <p>
                                @item.Descripcion
                            </p>
                            <label>Cantidad:</label>
                            <input type="number" id="cantidad__@item.IdMenu" min="1" max="99" name="cantidad" value="1" required class="form-control" />
                            @if (item.TipoMenu.ToString().Contains("Bebidas") || item.TipoMenu.ToString().Contains("Postres") || item.TipoMenu.ToString().Contains("Sopas")) { }
                            else
                            {
                                <label class="control-label">Termino:</label>
                                <select name="term" id="termi" class="form-control input-rounded">
                                    <option value="N">Ninguno</option>
                                    <option value="TR">Término Rojo</option>
                                    <option value="TM">Término Medio</option>
                                    <option value="TT">Término 3/4</option>
                                    <option value="BC">Bien Cocido</option>
                                    <option value="AC">Al Carbón</option>
                                </select>
                            }


                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                            <button type="button" onclick="addOrden(@item.IdMenu, '@item.Nombre','cantidad__@item.IdMenu' , @item.Precio)" class="btn btn-green">Agregar</button>
                            
                        </div>
                    </div>
                </div>
            </div>

            }
            </div>
    </div>
</div>

<script>
    function Filter(text) {
        if (text == ".all") {
            $(".all").show()
            return;
        }
        $(".all").hide()
        $(text).show();
    }

    function addOrden(id, producto, cantidad, precio, estado/*, term*/) {
        try {
            var ccantidad = parseFloat($("#" + cantidad).val());
            //var terminoo = String(term);
            var detalle = `
            <tr id="tr`+ id + `">
                <td>`+ id + `
                    <input type="hidden" value='`+ id +`' name="id[]">
                    <input type="hidden" value='`+ ccantidad +`' name="cantidad[]">
                </td>
                <td>`+ producto + `</td>
               
                <td>`+ estado + `</td>
                <td>`+ ccantidad + `</td>
                <td> $`+ precio + `</td>
                <td>$`+ (ccantidad * precio) + `</td>
                <td></td>
            </tr>
        `;

            $("#tr" + id).remove();

            $("#detalle").append(detalle);
            alert("Agregado Exitosamente");
        }
        catch (ex) {
            alert(ex);
        }

    }
</script>

VLO/Views/Ordenes/Ordenes.cshtml
@model VLO.Models.CocinaViewModel

@{
    ViewBag.Title = "Ordenes";
}

<h2>Ordenes</h2>

<div>
    <hr />
    <div class="row col-md-12">
        @foreach (var item in Model.pedidos)
        {
            <div class="thumbnail col-md-4">
                <div class="caption">
                    Orden para la mesa: @item.Mesa.NumMesa
                </div>
                <div>
                    <p>Cliente: @item.Cliente</p>
                    @{ var Adet = Model.detalle.Where(x => x.IdPedido == item.IdPedido).ToList();}
                    @foreach (var item2 in Adet)
                    {

                        var Menu = Model.menus.Where(x => x.IdMenu == item2.IdMenu).FirstOrDefault();

                        <p>Menu: @Menu.Nombre</p>
                        <p>Cantidad: @item2.cantidad</p>
                        
                     <a class="btn btn-danger btn-rounded" href="/Ordenes/TerminarOrdenCocina?iddetalle=@item2.IdDetalle">Terminar</a>
                    }
                </div>
            </div>
        }
    </div>
</div>
@section scripts{
    <script>
setInterval(function () {
            window.location.reload();
        }, 50000
        );</script>
}

VLO/Views/Ordenes/OrdenesTerminadas.cshtml
@model VLO.Models.CocinaViewModel
@{
    ViewBag.Title = "OrdenesTerminadas";
}
<h2>Ordenes</h2>
<div>
    <hr />
    <div class="row col-md-12">
        @foreach (var item in Model.pedidos)
        {
        <div class="thumbnail col-md-4">
            <div class="caption">
                Orden para la mesa: @item.Mesa.NumMesa
            </div>
            <p>Cliente: @item.Cliente</p>
            @{ var Adet = Model.detalle.Where(x => x.IdPedido == item.IdPedido).ToList();}
            @foreach (var item2 in Adet)
            {

                var Menu = Model.menus.Where(x => x.IdMenu == item2.IdMenu).FirstOrDefault();

                <div>
                    <p>
                        Menu: @Menu.Nombre
                    </p>
                    <p>
                        Mesa numero: @item.Mesa.NumMesa
                    </p>
                    <p>
                        <strong>Estado: </strong>
                        @if (item2.Estado == 1)
                        {
                            <span class="badge badge-danger">
                                En Cocina
                            </span>
                        }
                        else if (item2.Estado == 2)
                        {
                            <span class="badge badge-success">
                                Terminado
                            </span>
                        }
                        else if (item2.Estado == 3)
                        {
                            <span class="badge badge-warning">
                                Esperando pago
                            </span>
                        }
                        else if (item2.Estado == 4)
                        {
                            <span class="badge badge-dark">
                                Pagado
                            </span>
                        }
                    </p>
                </div>
            }
            @*<a class="btn btn-block badge-primary btn-rounded" href="/Ordenes/OrdenesMeseros?idpedido=@item.IdPedido">Pagar</a>*@
            <form method="post" action="/Ordenes/OrdenesMeseros">
                <input type="hidden" value="@item.IdPedido" name="idpedido" />
                <input type="submit" value="Pagar" class="btn btn-danger btn-rounded" />
            </form>
        </div>
        }
    </div>
</div>
@section scripts{
    <script>setInterval(function () {
            window.location.reload();
        }, 50000
        );</script>
}

VLO/Views/Ordenes/Prueba.cshtml
@{
    ViewBag.Title = "Prueba";
}

<h2>Prueba</h2>